# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 20, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(406, 100, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(420, 230, 47, 13))
        self.label_5.setObjectName("label_5")
        self.btnecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnecrypt.setGeometry(QtCore.QRect(20, 400, 75, 23))
        self.btnecrypt.setObjectName("btnecrypt")
        self.btndecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btndecrypt.setGeometry(QtCore.QRect(160, 400, 75, 23))
        self.btndecrypt.setObjectName("btndecrypt")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(290, 400, 75, 23))
        self.btnsign.setObjectName("btnsign")
        self.btnverify = QtWidgets.QPushButton(self.centralwidget)
        self.btnverify.setGeometry(QtCore.QRect(410, 400, 75, 23))
        self.btnverify.setObjectName("btnverify")
        self.btnkeys = QtWidgets.QPushButton(self.centralwidget)
        self.btnkeys.setGeometry(QtCore.QRect(554, 400, 81, 23))
        self.btnkeys.setObjectName("btnkeys")
        self.txtplain = QtWidgets.QTextEdit(self.centralwidget)
        self.txtplain.setGeometry(QtCore.QRect(100, 80, 104, 71))
        self.txtplain.setObjectName("txtplain")
        self.txtcipher = QtWidgets.QTextEdit(self.centralwidget)
        self.txtcipher.setGeometry(QtCore.QRect(100, 200, 104, 71))
        self.txtcipher.setObjectName("txtcipher")
        self.txtinf = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinf.setGeometry(QtCore.QRect(500, 70, 104, 71))
        self.txtinf.setObjectName("txtinf")
        self.txtsign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsign.setGeometry(QtCore.QRect(500, 200, 104, 71))
        self.txtsign.setObjectName("txtsign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "rsa cipher"))
        self.label_2.setText(_translate("MainWindow", "plaintext"))
        self.label_3.setText(_translate("MainWindow", "ciphertext"))
        self.label_4.setText(_translate("MainWindow", "information"))
        self.label_5.setText(_translate("MainWindow", "signature"))
        self.btnecrypt.setText(_translate("MainWindow", "encrypt"))
        self.btndecrypt.setText(_translate("MainWindow", "decrypt"))
        self.btnsign.setText(_translate("MainWindow", "sign"))
        self.btnverify.setText(_translate("MainWindow", "verify"))
        self.btnkeys.setText(_translate("MainWindow", "generate keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
